# Generated by Django 2.0.3 on 2018-04-14 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkey', models.IntegerField()),
                ('sk_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('text', models.TextField(max_length=1000)),
                ('posted_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkey', models.IntegerField()),
                ('sk_id', models.IntegerField()),
                ('show_date', models.DateTimeField()),
                ('picture', models.ImageField(blank=True, upload_to='pictures/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmn.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, max_length=1000)),
                ('user_photo_file_name', models.CharField(max_length=255, null=True)),
                ('user_photo_type', models.CharField(max_length=255, null=True)),
                ('user_photo', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkey', models.IntegerField()),
                ('sk_id', models.IntegerField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('picture', models.ImageField(blank=True, upload_to='pictures/')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmn.Venue'),
        ),
        migrations.AddField(
            model_name='note',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmn.Show'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
